name: CI Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
# MAUI Android Build
  build-android:
    runs-on: windows-2022
    name: Android Build
    steps:

      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Setup .NET 7
        uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8
        with:
          dotnet-version: 7.0.x
          
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore material-inout-desktop.csproj

      - name: Build MAUI Android
        run: dotnet publish material-inout-desktop.csproj -c Release -f net7.0-android --no-restore

      - name: Upload Android Artifact
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: materialinout-android-ci-build
          path: bin/Release/net7.0-android/*Signed.a*

# MAUI Windows Build
  build-windows:
    runs-on: windows-2022
    name: Windows Build
    steps:

      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Setup .NET 7
        uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8
        with:
          dotnet-version: 7.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Install Sign Tool
        run: dotnet tool install AzureSignTool

      - name: Restore Dependencies
        run: dotnet restore material-inout-desktop.csproj -p:PublishReadyToRun=true

      - name: Build MAUI Windows
        run: dotnet publish material-inout-desktop.csproj -c Release -f net7.0-windows10.0.19041.0 --no-restore

# kvc should be the key name I guess, trying
# Maybe even the thumbprint would work
      - name: Sign MSIX
        run: dotnet tool run AzureSignTool -- sign -kvt "${{ secrets.AZUREKEYVAULTTENANTID }}" -kvu "${{ secrets.AZUREKEYVAULTURL }}" -kvi "${{ secrets.AZUREKEYVAULTCLIENTID }}" -kvs "${{ secrets.AZUREKEYVAULTCLIENTSECRET }}" -kvc "${{ secrets.AZUREKEYVAULTNAME }}" -tr http://timestamp.digicert.com -v bin/Release/net7.0-windows10.0.19041.0/win10-x64/AppPackages/material-inout-desktop_1.0.0.1_Test/material-inout-desktop_1.0.0.1_x64.msix

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: materialinout-windows-ci-build
          path: bin/Release/net7.0-windows10.0.19041.0/win10-x64/AppPackages/material-inout-desktop_1.0.0.1_Test/*.msix

# MAUI iOS Build
  build-ios:
    runs-on: macos-12
    name: iOS Build
    steps:

      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Setup .NET 7
        uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8
        with:
          dotnet-version: 7.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore material-inout-desktop.csproj

      - name: Build MAUI iOS
        run: dotnet build material-inout-desktop.csproj -c Release -f net7.0-ios --no-restore /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: materialinout-ios-ci-build
          path: bin/Release/net7.0-ios/iossimulator-x64/**/*.app

# MAUI MacCatalyst Build
  build-mac:
    runs-on: macos-12
    name: MacCatalyst Build
    steps:
    
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Setup .NET 7
        uses: actions/setup-dotnet@c0d4ad69d8bd405d234f1c9166d383b7a4f69ed8
        with:
          dotnet-version: 7.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore material-inout-desktop.csproj

      - name: Build MAUI MacCatalyst
        run: dotnet publish material-inout-desktop.csproj -c Release -f net7.0-maccatalyst --no-restore -p:BuildIpa=True

      - name: Upload MacCatalyst Artifact
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: materialinout-macos-ci-build
          path: bin/Release/net7.0-maccatalyst/maccatalyst-x64/publish/*.pkg
